TodoApp/Todo/urls.py
from django.conf.urls import include, url
from . import views

app_name = "Todo"

urlpatterns = [
    # it will take us upto the index page of the website.
    url(r'^$', views.IndexView.as_view(), name="index"),

    # this will open a form to create new tasks
    url(r'dailyworks-add/$', views.DailyWorksCreate.as_view(), name='dailyworks_add'),

    # /Todo/dailyworks/2/delete/
    url(r'^(?P<work_id>[0-9]+)/delete-dailyworks/$', views.delete_dailyworks, name='delete_dailyworks'),

    # url to delete all the Tasks at once
    url(r'^dailyworks-deleteAll/$', views.DeleteAllDailyWorks, name='dailyworks_deleteAll'),

]

TodoApp/TodoApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^Todo/', include('Todo.urls')),
    url(r'^', include('Todo.urls')),
    #url(r'^dailyworks/', include('Todo.urls')),
]

TodoApp/Todo/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from django.utils import timezone



class DailyWorks(models.Model):
     goal = models.CharField(max_length=200)
     date = models.DateField(auto_now_add=False, auto_now=False, blank=True, default=timezone.now())
     completed = models.BooleanField(default=False)

     def get_absolute_url(self):
          return reverse('Todo:index')

     def __repr__(self):
          return self.goal+" - "+str(self.date)

TodoApp/users/models.py
from django.db import models

# Create your models here.

TodoApp/Todo/forms.py
from django import forms
from django.forms import ModelForm

from .models import DailyWorks


class DateInput(forms.DateInput):
    input_type = 'date'


class DailyWorksForm(ModelForm):
    class Meta:
        model = DailyWorks
        fields = ['goal', 'date', 'completed']
        widgets = {
            'date': DateInput(),
        }

TodoApp/Todo/views.py
from django.views.generic.edit import CreateView
from django.views import generic
from .models import DailyWorks
from .forms import DailyWorksForm
from django.shortcuts import render




class IndexView(generic.ListView):
    template_name = 'Todo/index.html'
    context_object_name = 'all_tasks'

    def get_queryset(self):
        return DailyWorks.objects.all()


class DailyWorksCreate(CreateView):
    model = DailyWorks
    form_class = DailyWorksForm



def delete_dailyworks(request, work_id):
    item = DailyWorks.objects.get(id=work_id)
    item.delete()
    items = DailyWorks.objects.filter()
    return render(request, 'Todo/index.html', {'all_tasks': items})


def DeleteAllDailyWorks(request):
    items = DailyWorks.objects.all()
    items.delete()
    return render(request, 'Todo/index.html')

TodoApp/users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    form = UserCreationForm()
    return render(request, 'users/register.html', {'form': form})

TodoApp/Todo/templates/Todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Todo App{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'Todo/style.css' %}"/>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Headers-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="{% url 'Todo:index' %}"><span class="glyphicon glyphicon-time" aria-hidden="true"></span> Todo App</a>
        </div>
        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'Todo:dailyworks_add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        Add Tasks
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'Todo:dailyworks_deleteAll' %}">
                        <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
                        Remove All Tasks
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}

{% endblock %}

</body>
</html>

TodoApp/Todo/templates/Todo/dailyworks_form.html
{% extends 'Todo/base.html' %}
{% block title %}Add New Tasks{% endblock %}
{% block tasks_active %}active{% endblock %}

{% block body %}
    <div class="Container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'Todo/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Add</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

TodoApp/Todo/templates/Todo/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

TodoApp/Todo/templates/Todo/index.html
{% extends 'Todo/base.html' %}
{% block body %}
    <ul>
        <div class="list-group">
            {% for work in all_tasks %}
                <li>
                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start active">
                        <div class="d-flex w-100 justify-content-between">
                            {% if work.completed == True %}
                                <h6 id="Completed" class="mb-1">Completed Task</h6>
                            {% else %}
                                <h6 id="Pending" class="mb-1">Pending Task</h6>
                            {% endif %}
                            <h4 class="mb-1">{{ work.goal }}</h4>
                            <h5>{{ work.date }}</h5>
                            <!-- Button to remove tasks-->
                            <form action="{% url 'Todo:delete_dailyworks' work.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="work_id" value="{{ work.id }}"/>
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>Remove
                                </button>
                            </form>

                        </div>

                   </a>
                </li>
                <br>
            {% endfor %}
        </div>
    </ul>
{% endblock %}

TodoApp/users/templates/users/register.html
{% extends "Todo/base.html" %}
{% block content %}
    <div class=""

{% endblock content %}